### ISSUE TITLE
multiple optical drives?

### ISSUE THREAD

**Issue by emmakat** [git-developer/marvyn#3] opened 2020-05-21 03:28 UTC
Thank you again for responding to my inquiry, I appreciate it! I seem to have worked out many of the getting started hiccups. 

One big question I have is whether this project can support multiple drives, and rip from each of them. I have a blu ray drive, a regular dvd drive, and 5 optical drives. When I add all of the drives, or even 1 additional drive, it causes my working rip (the blu ray) to fail. Based on https://askubuntu.com/questions/921235/udev-rules-for-launching-scripts-when-dvd-loaded-multiple-drives and what I see in udev disc detection rules, it _appears_ as though it does support multiple drives. 

I have a makemkv container which if I run it without loading any drives, it will tell me what I have available but didn't expose to the container. (I used this to inform what I put in rip-disc.yml) 
```
cont-init.d] 95-check-optical-drive.sh: executing... 
[cont-init.d] 95-check-optical-drive.sh: looking for usable optical drives...
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr0, /dev/sg0], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr0 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg0 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr2, /dev/sg3], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr2 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg3 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr3, /dev/sg4], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr3 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg4 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr4, /dev/sg5], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr4 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg5 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr5, /dev/sg6], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr5 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg6 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr6, /dev/sg7], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr6 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg7 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh: found optical drive [/dev/sr1, /dev/sg2], but it is not usable because:
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sr1 is not exposed to the container.
[cont-init.d] 95-check-optical-drive.sh:   --> the host device /dev/sg2 is not exposed to the container.
```

**Based on this, I loaded this into the rip-disc.yml. I have commented out everything except the blu ray device though, because when I try to include even 1 additional drive, nothing works.**

```
devices:
      - /dev/cdrom:/dev/cdrom
      - /dev/dvd:/dev/dvd
      - /dev/sg0:/dev/sg0
      - /dev/sr0:/dev/sr0
    #  - /dev/sg2:/dev/sg2
    #  - /dev/sr1:/dev/sr1
    #  - /dev/sg3:/dev/sg3
    #  - /dev/sr2:/dev/sr2
    #  - /dev/sg4:/dev/sg4
    #  - /dev/sr3:/dev/sr3
    #  - /dev/sg5:/dev/sg5
    #  - /dev/sr4:/dev/sr4
    #  - /dev/sg6:/dev/sg6
    #  - /dev/sr5:/dev/sr5
    #  - /dev/sg7:/dev/sg7
    #  - /dev/sr6:/dev/sr6
```
`2020-05-21T03:22:33.614239038Z Error 'Scsi error - NOT READY:MEDIUM NOT PRESENT - TRAY OPEN' occurred while reading '/BDMV/STREAM/00800.m2ts' at offset '2626289664'
2020-05-21T03:22:34.014817843Z Backup failed
2020-05-21T03:22:34.014833119Z Backup failed.
2020-05-21T03:22:34.149328316Z Kopie von 'ATTACK_OF_THE_CLONES' mit Erfolg beendet.
`
It was happily ripping Attack of the clones, then I opened one of the cdrom drives, and put music disc in there. It immediately crashed the bluray rip and gave me the above error.

**Comment by git-developer** [comment] 2020-05-21 06:50
Multiple drives are currently not supported because the drive to use (e.g. `/dev/sr0` or `/dev/sg1`) is not specified explicitely at the moment.

It should be possible to implement that feature. Things to consider:
* The `udev` rule has to be extended to give the device name as argument to `bin/rip-disc`.
* The `main()` function in `services/rip-disc` has to be extended to read the first argument and give it to the ripper applications.
* Since `rip-disc` uses a timestamp in the container name, it should be safe to run multiple containers concurrently, as long as discs differ and at least 1 second lies between starts.

Please don't expect an implementation in the near future. I'm currently quite busy, and testing would be a challenge because I own just a single drive. I'd like to encourage you to implement the feature and create a pull request against branch `develop`.

**Comment by git-developer** [comment] 2020-05-23 12:18
The feature is now implemented in branch [develop](https://github.com/git-developer/marvyn/tree/develop) (commit [51aa173](https://github.com/git-developer/marvyn/commit/51aa173dfcd916fe7c3776715e1b0423e4b2864f)). @emmakat Please try and report back.

**Comment by emmakat** [comment] 2020-05-23 15:26
wow! that's amazing - thank you! I will try it today.

**Comment by emmakat** [comment] 2020-05-23 17:17
So far so good. First, a compliment: The instructions work out of the box with no modifications! I'm currently ripping a bluray and it's proceeding nicely. 
I will try multiple drive configuration next (it gave me errors initially, will try again shortly).

**Comment by git-developer** [comment] 2020-05-29 04:54
@emmakat Could you give a short status report?

**Comment by emmakat** [comment] 2020-05-30 17:10
Yes, so sorry for the delay. I will re-run with multiple drives later today and give you an update.

**Comment by emmakat** [comment] 2020-05-30 17:10
and thank you again for working on this! I know you're busy, but it's just awesome that you took the time to add this feature.

**Comment by emmakat** [comment] 2020-06-01 02:33
SUCCESS! I'm happily ripping 3 disks at the moment. The order in which they are listed in rip-disk.yml is important. The /dev/sg1 has to be listed first, then the /dev/sr1, if you put it the other way around, it fails. Thank you!!

**Comment by git-developer** [comment] 2020-06-01 11:20
Thanks for your feedback!

I don't understand why the order of devices should make any difference... is an error message returned?

If you think that the issue is solved, please close it.

**Closed as completed** 2020-06-01 21:12 UTC
